### ISSUE TITLE
Buffer overflow in GeoIPCity.c (and maybe elsewhere)

### ISSUE THREAD

**Issue by markwj** [maxmind/geoip-api-c#117]
The GeoIPCity.c code includes:

`const int       FULL_RECORD_LENGTH = 50;`

However, long city names can easily make the encoded record longer. For example:

`$ geoiplookup -f GeoIPCity.dat 187.228.11.0
GeoIP City Edition, Rev 1: MX, MOR, Unidad Habitacional Jose Maria Morelos y Pavo, N/A, -180.000000, -179.155197, 0, 0`

That city name is 46 bytes, and the metadata takes it over the record length limit causing the latitude and longitude at the end to be corrupted. An attacker with control over the GetIPCity.dat file could presumably exploit (although untested).

A quick nasty workaround to increase FULL_RECORD_LENGTH to 128, yields the correct result:

`$ geoiplookup -f /GeoIPCity.dat 187.228.11.0
GeoIP City Edition, Rev 1: MX, MOR, Unidad Habitacional Jose Maria Morelos y Pavon, 62662, 18.622801, -99.317001, 0, 0`

A better approach would be to (a) ensure adequate buffer size for the longest record, and (b) add checks to ensure the buffer is not overflowed when parsing the record.

**Comment by oschwald** [comment]
Thank you for bringing this to our attention, @markwj . We recognize the issue. Because we don't expect this would be an issue with our official legacy databases and because we're moving to end of life the legacy databases in less than a year, we have decided not to fix this issue.

We strongly recommend that those using our legacy databases switch to using our GeoIP2 databases as soon as possible. This will address the security concern and also ensure the no disruption occurs when the legacy databases are end-of-lifed in May 2022.

**Comment by oschwald** [comment]
Given that the legacy database format will be [retired in May](https://blog.maxmind.com/2020/06/retirement-of-geoip-legacy-downloadable-databases-in-may-2022), it seems unlikely that this will be fixed. I am going to go ahead and close this issue. Thank you for reporting; I apologize that it was never addressed.
